image: alpine/edge
packages:
- go
- scdoc
sources:
- https://git.sr.ht/~rjarry/aerc
tasks:
- checkfmt: |
    cd aerc
    make checkfmt
- build: |
    cd aerc
    make
- test: |
    cd aerc
    go test ./...
